### ISSUE TITLE
Listing on PyPI?

### ISSUE THREAD

**Issue by ghost** [GTmmiller/backlog_puller#1]
Being able to install the library using pip or easy_install would make it a lot easier to use it in a wide variety of projects. Have you considered this?

**Comment by GTmmiller** [comment]
I thought about doing that when I first wrote backloggery-puller, but I didn't go through with it at the time. Since you're asking about it I'll try to make it a PyPi package over the weekend. Thanks for expressing interest in the project!

**Comment by ghost** [comment]
Thanks a lot! :smiley:

**Comment by GTmmiller** [comment]
I just got done fixing the project up and adding the package to PyPi. I changed the name to `backlog_puller` since it's shorter and python modules can't have hyphens in the title. All you have to do now is `pip install backlog_puller` and you should be able to use the project! Thanks again for asking me to list this on PyPi!
